### ISSUE TITLE
reicht da nicth ein normaler seedhandler?

### ISSUE THREAD

**Issue by martin-raden** [RickGelhausen/IntaRNA#18]
https://github.com/RickGelhausen/IntaRNA/blob/ca25982114c81abbafef900d45022f9392e7dcf0/src/IntaRNA/HelixHandler.h#L7

hier musst doch nirgends indices verschieben oder?

**Comment by RickGelhausen** [comment]
Jo das ist korrekt, das wird nirgends benutzt.
Ist im nächsten commit ersetzt.
